/**
 * Seed data for the ops hospital registry — transcribed verbatim from the
 * design prototype's `OpsDB.hospitals` (Ops.jsx). Hospital id 13 is this
 * mbAdmin instance (Apollo, `APOLLO_HID`).
 */
import type {
  KycDocKey,
  OpsHospital,
} from '@/features/ops-hospitals/application/store/hospitals.types';

export const OPS_HOSPITALS: readonly OpsHospital[] = [
  {
    id: 1,
    name: 'Sunrise Multispeciality',
    email: 'admin@sunrisemsp.in',
    phone: '+91 98220 44315',
    gstin: '27AABCS4821F1Z3',
    plan: 'Growth',
    city: 'Pune',
    st: 'MH',
    bookings: 4280,
    onboarded: 'June 04, 2026',
    status: 'Active',
    bank: {
      bank: 'ICICI Bank',
      account: '023305001188',
      ifsc: 'ICIC0000233',
      upi: 'sunrisemsp@icici',
    },
  },
  {
    id: 2,
    name: 'Lotus Heart Institute',
    email: 'ops@lotusheart.in',
    phone: '+91 98410 22876',
    gstin: '33AACCL2214B1Z8',
    plan: 'Enterprise',
    city: 'Chennai',
    st: 'TN',
    bookings: 6120,
    onboarded: 'June 02, 2026',
    status: 'Pending verification',
    kyc: { reg: 'Submitted', gst: 'Submitted', licence: 'Submitted', bankproof: 'Submitted' },
    bank: {
      bank: 'Axis Bank',
      account: '917010045522',
      ifsc: 'UTIB0000101',
      upi: 'lotusheart@axisb',
    },
  },
  {
    id: 3,
    name: 'Kaveri General Hospital',
    email: 'contact@kaverigen.in',
    phone: '+91 97390 18452',
    gstin: '29AABCK1183E1Z6',
    plan: 'Starter',
    city: 'Mysuru',
    st: 'KA',
    bookings: 1240,
    onboarded: 'May 29, 2026',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Nirmal Ortho & Spine',
    email: 'admin@nirmalortho.in',
    phone: '+91 94250 77031',
    gstin: '23AADCN7745A1Z2',
    plan: 'Growth',
    city: 'Indore',
    st: 'MP',
    bookings: 2860,
    onboarded: 'May 27, 2026',
    status: 'Suspended',
    suspension: {
      reason: 'Manual review',
      since: '2026-06-08',
      by: 'riya.sharma@medibook.in',
      note: 'Repeated patient complaints under investigation.',
    },
  },
  {
    id: 5,
    name: "Ashwini Children's Care",
    email: 'hello@ashwinicare.in',
    phone: '+91 98470 63219',
    gstin: '32AAECA5530C1Z1',
    plan: 'Starter',
    city: 'Kochi',
    st: 'KL',
    bookings: 980,
    onboarded: 'May 24, 2026',
    status: 'Pending verification',
    kyc: { reg: 'Submitted', gst: 'Missing', licence: 'Submitted', bankproof: 'Submitted' },
  },
  {
    id: 6,
    name: 'Meridian City Hospital',
    email: 'desk@meridiancity.in',
    phone: '+91 98200 91145',
    gstin: '27AAACM9082D1Z4',
    plan: 'Enterprise',
    city: 'Mumbai',
    st: 'MH',
    bookings: 7450,
    onboarded: 'May 21, 2026',
    status: 'Active',
    bank: { bank: 'SBI', account: '38220145577', ifsc: 'SBIN0005943', upi: 'meridiancity@sbi' },
  },
  {
    id: 7,
    name: 'Vasudha Medical Centre',
    email: 'care@vasudhamed.in',
    phone: '+91 99485 30672',
    gstin: '36AAFCV3319G1Z9',
    plan: 'Growth',
    city: 'Hyderabad',
    st: 'TS',
    bookings: 3320,
    onboarded: 'May 18, 2026',
    status: 'Active',
    bank: {
      bank: 'HDFC Bank',
      account: '50200077665544',
      ifsc: 'HDFC0002210',
      upi: 'vasudhamed@hdfcbank',
    },
  },
  {
    id: 8,
    name: 'Trinity Care & Research',
    email: 'info@trinitycare.in',
    phone: '+91 98860 41520',
    gstin: '29AABCT6650H1Z0',
    plan: 'Custom — Trinity Care',
    city: 'Bengaluru',
    st: 'KA',
    bookings: 5210,
    onboarded: 'May 12, 2026',
    status: 'Active',
    bank: {
      bank: 'Kotak Bank',
      account: '7311550022',
      ifsc: 'KKBK0000958',
      upi: 'trinitycare@kotak',
    },
  },
  {
    id: 9,
    name: 'Girnar Multispeciality',
    email: 'admin@girnarmsp.in',
    phone: '+91 98250 84413',
    gstin: '24AACCG8821K1Z5',
    plan: 'Starter',
    city: 'Rajkot',
    st: 'GJ',
    bookings: 860,
    onboarded: 'May 08, 2026',
    status: 'Suspended',
    graceDays: 5,
    suspension: {
      reason: 'Non-payment',
      since: '2026-06-05',
      invoiceNo: 'INV-2026-0239',
      by: 'riya.sharma@medibook.in',
      note: 'May subscription unpaid past the grace window.',
    },
  },
  {
    id: 10,
    name: 'Padma Eye Foundation',
    email: 'appointments@padmaeye.in',
    phone: '+91 98660 12908',
    gstin: '37AADCP5512M1Z7',
    plan: 'Starter',
    city: 'Vijayawada',
    st: 'AP',
    bookings: 640,
    onboarded: 'May 03, 2026',
    status: 'Rejected',
    rejectReason: 'Incomplete KYC documents',
    kyc: { reg: 'Submitted', gst: 'Submitted', licence: 'Missing', bankproof: 'Submitted' },
  },
  {
    id: 11,
    name: 'Himgiri Wellness Hospital',
    email: 'front@himgiriwell.in',
    phone: '+91 97560 40287',
    gstin: '05AABCH3308N1Z2',
    plan: 'Growth',
    city: 'Dehradun',
    st: 'UK',
    bookings: 1980,
    onboarded: 'April 26, 2026',
    status: 'Active',
    bank: { bank: 'PNB', account: '0158002100334455', ifsc: 'PUNB0015800', upi: 'himgiriwell@pnb' },
  },
  {
    id: 12,
    name: 'Charak Institute of Medicine',
    email: 'admin@charakim.in',
    phone: '+91 99350 71634',
    gstin: '09AACCC7761P1Z6',
    plan: 'Enterprise',
    city: 'Lucknow',
    st: 'UP',
    bookings: 4890,
    onboarded: 'April 20, 2026',
    status: 'Pending verification',
    kyc: { reg: 'Submitted', gst: 'Submitted', licence: 'Submitted', bankproof: 'Submitted' },
    bank: {
      bank: 'Canara Bank',
      account: '110023456789',
      ifsc: 'CNRB0001100',
      upi: 'charakim@canara',
    },
  },
  {
    id: 14,
    name: 'Sahyadri Speciality Hospital',
    email: 'admin@sahyadrispeciality.in',
    phone: '+91 97640 21188',
    gstin: '27AAGCS6642R1Z4',
    plan: 'Starter',
    city: 'Nashik',
    st: 'MH',
    bookings: 0,
    onboarded: 'June 11, 2026',
    status: 'Pending verification',
  },
  {
    id: 13,
    name: 'Apollo Hospital',
    email: 'contact@apollo.med',
    phone: '080 4567 8900',
    plan: 'Growth',
    city: 'Bengaluru',
    st: 'KA',
    bookings: 3120,
    onboarded: 'April 12, 2025',
    status: 'Active',
  },
];

/** KYC document slots + display labels (design `KYC_DOCS`). */
export const KYC_DOCS: readonly (readonly [KycDocKey, string])[] = [
  ['reg', 'Registration certificate'],
  ['gst', 'GST certificate'],
  ['licence', 'Medical licence'],
  ['bankproof', 'Bank account proof'],
];
