/**
 * Registry of every Lucide glyph the Medibook design uses, keyed by the
 * kebab-case name that appears in the design source. Static imports keep the
 * bundle tree-shakeable (importing the whole `icons` map would not be).
 * Adding a glyph = one import + one map entry.
 */
import {
  Activity,
  ArrowLeft,
  Ban,
  Banknote,
  Bell,
  BellRing,
  BookOpen,
  Building,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleSlash,
  CircleX,
  Clock,
  Contact,
  Copy,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  FileDown,
  FileText,
  Footprints,
  Gauge,
  GitBranch,
  Hash,
  Headset,
  Hourglass,
  House,
  Image,
  ImagePlus,
  IndianRupee,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Megaphone,
  MessageCircle,
  Monitor,
  Pause,
  Pencil,
  Percent,
  Phone,
  Plane,
  Play,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Star,
  Stethoscope,
  Ticket,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

export const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  ban: Ban,
  banknote: Banknote,
  bell: Bell,
  'bell-ring': BellRing,
  'book-open': BookOpen,
  building: Building,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'calendar-x': CalendarX,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'circle-slash': CircleSlash,
  'circle-x': CircleX,
  clock: Clock,
  contact: Contact,
  copy: Copy,
  'credit-card': CreditCard,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-down': FileDown,
  'file-text': FileText,
  footprints: Footprints,
  gauge: Gauge,
  'git-branch': GitBranch,
  hash: Hash,
  headset: Headset,
  hourglass: Hourglass,
  house: House,
  image: Image,
  'image-plus': ImagePlus,
  'indian-rupee': IndianRupee,
  info: Info,
  'key-round': KeyRound,
  landmark: Landmark,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'life-buoy': LifeBuoy,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'mail-check': MailCheck,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  monitor: Monitor,
  pause: Pause,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  plane: Plane,
  play: Play,
  plus: Plus,
  printer: Printer,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'skip-forward': SkipForward,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  smile: Smile,
  star: Star,
  stethoscope: Stethoscope,
  ticket: Ticket,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'undo-2': Undo2,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  wallet: Wallet,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
