/**
 * Seed data for ops reports — the six report definitions, their rows and
 * their last-generated dates, transcribed from the design prototype
 * (`OpsReports` defs + `OpsDB.reportsGen` in Ops.jsx) and extended with the
 * actual report contents.
 *
 * Audit 3.1.4: the download button used to fire a "ready" toast and write no
 * file. Every definition now carries the `columns` + `rows` the export is
 * made of, so `downloadCsv` has something real to write and the screen may
 * legitimately say "Exported". Hospital names, departments, doctors, booking
 * references and the receipt/invoice series follow the canonical master data.
 */
import type { CsvCell } from '@/shared/lib/download';
import type { IconName } from '@/shared/ui/icon-registry';

/**
 * Accent tint of a report card's icon box — literal keys of the shared
 * `OPS_TINTS` map (`@/shared/ui/OpsConfirm`).
 */
export type OpsReportTint = 'primary' | 'info' | 'success' | 'warning' | 'danger' | 'neutral';

/** One exportable platform report definition. */
export interface OpsReportDef {
  readonly name: string;
  readonly desc: string;
  readonly icon: IconName;
  readonly tint: OpsReportTint;
  /** Filename stem of the exported CSV (no extension). */
  readonly file: string;
  /** Header row of the export. */
  readonly columns: readonly string[];
  /** Body rows, index-aligned with `columns`. */
  readonly rows: readonly (readonly CsvCell[])[];
}

export const OPS_REPORT_DEFS: readonly OpsReportDef[] = [
  {
    name: 'Revenue Report',
    desc: 'Platform revenue by hospital, plan and period.',
    icon: 'indian-rupee',
    tint: 'success',
    file: 'medibook-revenue-report',
    columns: [
      'Invoice',
      'Hospital',
      'Plan',
      'Period',
      'Subscription (INR)',
      'Commission (INR)',
      'GST 18% (INR)',
      'Total (INR)',
      'Status',
    ],
    rows: [
      [
        'INV-2026-0231',
        'Sunrise Multispeciality',
        'Growth',
        'May 2026',
        18000,
        42800,
        10944,
        71744,
        'Paid',
      ],
      [
        'INV-2026-0232',
        'Lotus Heart Institute',
        'Enterprise',
        'May 2026',
        45000,
        61200,
        19116,
        125316,
        'Paid',
      ],
      [
        'INV-2026-0233',
        'Kaveri General Hospital',
        'Starter',
        'May 2026',
        6000,
        12400,
        3312,
        21712,
        'Paid',
      ],
      [
        'INV-2026-0234',
        'Meridian City Hospital',
        'Enterprise',
        'May 2026',
        45000,
        74500,
        21510,
        141010,
        'Paid',
      ],
      [
        'INV-2026-0235',
        'Trinity Care & Research',
        'Growth',
        'May 2026',
        18000,
        52100,
        12618,
        82718,
        'Overdue',
      ],
      ['INV-2026-0236', 'Apollo Hospital', 'Growth', 'May 2026', 18000, 31200, 8856, 58056, 'Paid'],
      [
        'INV-2026-0237',
        'Charak Institute of Medicine',
        'Growth',
        'May 2026',
        18000,
        48900,
        12042,
        78942,
        'Pending',
      ],
      [
        'INV-2026-0238',
        'Padma Eye Foundation',
        'Starter',
        'May 2026',
        6000,
        9800,
        2844,
        18644,
        'Paid',
      ],
    ],
  },
  {
    name: 'Bookings Report',
    desc: 'All bookings with department and outcome detail.',
    icon: 'calendar-check',
    tint: 'primary',
    file: 'medibook-bookings-report',
    columns: [
      'Booking Ref',
      'Token',
      'Hospital',
      'Department',
      'Doctor',
      'Date',
      'Status',
      'Fee (INR)',
      'Channel',
    ],
    rows: [
      [
        'MB-2026-000118',
        'T-004',
        'Apollo Hospital',
        'Cardiology',
        'Dr. Thomas Kurian',
        '2026-06-11',
        'Completed',
        800,
        'Medibook',
      ],
      [
        'MB-2026-000119',
        'T-007',
        'Apollo Hospital',
        'General Medicine',
        'Dr. Anil Kumar',
        '2026-06-11',
        'Completed',
        500,
        'Medibook',
      ],
      [
        'MB-2026-000120',
        'T-011',
        'City Care Clinic',
        'Pediatrics',
        'Dr. Kumar Venkat',
        '2026-06-12',
        'No-show',
        600,
        'Medibook',
      ],
      [
        'MB-2026-000121',
        'T-002',
        'Sunrise Multispeciality',
        'Orthopedics',
        'Dr. Geetha Rao',
        '2026-06-12',
        'Completed',
        700,
        'Walk-in',
      ],
      [
        'MB-2026-000122',
        'T-014',
        'Apollo Hospital',
        'Neurology',
        'Dr. Maya Suresh',
        '2026-06-12',
        'Cancelled',
        1000,
        'Medibook',
      ],
      [
        'MB-2026-000123',
        'T-005',
        'City Care Clinic',
        'ENT',
        'Dr. Arun Bhat',
        '2026-06-13',
        'In Queue',
        500,
        'Medibook',
      ],
      [
        'MB-2026-000124',
        'T-009',
        'Apollo Hospital',
        'Dermatology',
        'Dr. Leela Pillai',
        '2026-06-13',
        'Scheduled',
        650,
        'Medibook',
      ],
      [
        'MB-2026-000125',
        'T-012',
        'Apollo Hospital',
        'Cardiology',
        'Dr. Anya Sharma',
        '2026-06-13',
        'Scheduled',
        900,
        'Medibook',
      ],
      [
        'MB-2026-000126',
        'T-003',
        'City Care Clinic',
        'General Medicine',
        'Dr. Meera Nair',
        '2026-06-13',
        'Scheduled',
        450,
        'Walk-in',
      ],
      [
        'MB-2026-000127',
        'T-016',
        'Lakeside Hospital',
        'Orthopedics',
        'Dr. Geetha Rao',
        '2026-06-14',
        'Scheduled',
        700,
        'Medibook',
      ],
    ],
  },
  {
    name: 'Onboarding Report',
    desc: 'Hospital onboarding funnel and KYC status.',
    icon: 'building-2',
    tint: 'info',
    file: 'medibook-onboarding-report',
    columns: [
      'Hospital',
      'City',
      'Plan',
      'Applied On',
      'Registration',
      'GST',
      'Licence',
      'Bank Proof',
      'Status',
    ],
    rows: [
      [
        'Lotus Heart Institute',
        'Chennai',
        'Enterprise',
        '2026-06-02',
        'Submitted',
        'Submitted',
        'Submitted',
        'Submitted',
        'Pending verification',
      ],
      [
        'Girnar Multispeciality',
        'Ahmedabad',
        'Growth',
        '2026-06-05',
        'Verified',
        'Submitted',
        'Missing',
        'Submitted',
        'Pending verification',
      ],
      [
        'Himgiri Wellness Hospital',
        'Dehradun',
        'Starter',
        '2026-06-07',
        'Missing',
        'Missing',
        'Missing',
        'Missing',
        'Rejected',
      ],
      [
        'Sunrise Multispeciality',
        'Pune',
        'Growth',
        '2026-05-28',
        'Verified',
        'Verified',
        'Verified',
        'Verified',
        'Active',
      ],
      [
        'Kaveri General Hospital',
        'Mysuru',
        'Starter',
        '2026-05-24',
        'Verified',
        'Verified',
        'Verified',
        'Verified',
        'Active',
      ],
      [
        'Meridian City Hospital',
        'Hyderabad',
        'Enterprise',
        '2026-05-19',
        'Verified',
        'Verified',
        'Verified',
        'Verified',
        'Active',
      ],
      [
        'Nirmal Ortho & Spine',
        'Nagpur',
        'Growth',
        '2026-05-16',
        'Verified',
        'Verified',
        'Missing',
        'Verified',
        'Suspended',
      ],
      [
        'Apollo Hospital',
        'Bengaluru',
        'Growth',
        '2026-05-12',
        'Verified',
        'Verified',
        'Verified',
        'Verified',
        'Active',
      ],
    ],
  },
  {
    name: 'Settlement Statement',
    desc: 'Payout history with commission breakdown.',
    icon: 'landmark',
    tint: 'warning',
    file: 'medibook-settlement-statement',
    columns: [
      'Statement',
      'Hospital',
      'Period',
      'Gross (INR)',
      'Commission 10% (INR)',
      'Net Payable (INR)',
      'Expected',
      'Released On',
      'UTR',
      'Status',
    ],
    rows: [
      [
        'STL-2026-0091',
        'Sunrise Multispeciality',
        '01–07 Jun 2026',
        428000,
        42800,
        385200,
        '2026-06-13',
        '2026-06-13',
        'UTR26-0091R',
        'Released',
      ],
      [
        'STL-2026-0092',
        'Meridian City Hospital',
        '01–07 Jun 2026',
        745000,
        74500,
        670500,
        '2026-06-13',
        '2026-06-13',
        'UTR26-0092R',
        'Received',
      ],
      [
        'STL-2026-0093',
        'Trinity Care & Research',
        '01–07 Jun 2026',
        521000,
        52100,
        468900,
        '2026-06-13',
        null,
        null,
        'Pending',
      ],
      [
        'STL-2026-0094',
        'Kaveri General Hospital',
        '01–07 Jun 2026',
        124000,
        12400,
        111600,
        '2026-06-13',
        null,
        null,
        'Payout failed',
      ],
      [
        'STL-2026-0095',
        'Apollo Hospital',
        '01–07 Jun 2026',
        312000,
        31200,
        280800,
        '2026-06-20',
        null,
        null,
        'Pending',
      ],
      [
        'STL-2026-0088',
        'Sunrise Multispeciality',
        '25–31 May 2026',
        396000,
        39600,
        356400,
        '2026-06-06',
        '2026-06-06',
        'UTR26-0088R',
        'Received',
      ],
      [
        'STL-2026-0089',
        'Padma Eye Foundation',
        '25–31 May 2026',
        98000,
        9800,
        88200,
        '2026-06-06',
        '2026-06-06',
        'UTR26-0089R',
        'Received',
      ],
      [
        'STL-2026-0090',
        'Charak Institute of Medicine',
        '25–31 May 2026',
        489000,
        48900,
        440100,
        '2026-06-06',
        '2026-06-09',
        'UTR26-0090R',
        'Released',
      ],
    ],
  },
  {
    name: 'Compliance Audit',
    desc: 'Full audit trail of sensitive platform actions.',
    icon: 'scroll-text',
    tint: 'danger',
    file: 'medibook-compliance-audit',
    columns: ['Timestamp', 'Actor', 'Module', 'Action', 'Scope', 'IP Address', 'Severity'],
    rows: [
      [
        '2026-06-13 09:42',
        'riya.sharma@medibook.in',
        'Hospitals',
        'Hospital suspended — Nirmal Ortho & Spine',
        'Nirmal Ortho & Spine',
        '10.42.8.11',
        'Critical',
      ],
      [
        '2026-06-12 17:05',
        'riya.sharma@medibook.in',
        'Settlements',
        'Settlement released — STL-2026-0092',
        'Meridian City Hospital',
        '10.42.8.11',
        'Info',
      ],
      [
        '2026-06-12 15:31',
        'anil.kapoor@medibook.in',
        'Users & Roles',
        'Role permissions changed — Finance Admin',
        'Platform',
        '10.42.8.14',
        'Critical',
      ],
      [
        '2026-06-12 11:18',
        'unknown@23.94.61.2',
        'Auth',
        'Failed login attempt (3x)',
        'Ops console',
        '23.94.61.2',
        'Warning',
      ],
      [
        '2026-06-11 16:47',
        'meera.pillai@medibook.in',
        'Billing',
        'Invoice regenerated — INV-2026-0234',
        'Meridian City Hospital',
        '10.42.8.19',
        'Info',
      ],
      [
        '2026-06-11 12:03',
        'anil.kapoor@medibook.in',
        'Platform Users',
        'Patient account deleted — dev.trivedi@gmail.com',
        'Platform',
        '10.42.8.14',
        'Critical',
      ],
      [
        '2026-06-10 18:22',
        'meera.pillai@medibook.in',
        'Reports',
        'Data export — bookings FY 2025-26',
        'Platform',
        '10.42.8.19',
        'Warning',
      ],
      [
        '2026-06-10 02:00',
        'system@medibook.in',
        'Media',
        'Media purged — 214 orphaned files',
        'Platform',
        '10.42.0.1',
        'Warning',
      ],
      [
        '2026-06-09 10:40',
        'riya.sharma@medibook.in',
        'Settings',
        'API key rotated — payments gateway',
        'Platform',
        '10.42.8.11',
        'Info',
      ],
      [
        '2026-06-08 09:12',
        'riya.sharma@medibook.in',
        'Settings',
        'Settings updated — payout schedule',
        'Platform',
        '10.42.8.11',
        'Info',
      ],
    ],
  },
  {
    name: 'Platform Users Report',
    desc: 'Registered end users, activity and growth.',
    icon: 'users',
    tint: 'neutral',
    file: 'medibook-platform-users-report',
    columns: [
      'User',
      'Email',
      'Mobile',
      'City',
      'Registered On',
      'Bookings',
      'Family Members',
      'Status',
    ],
    rows: [
      [
        'Ananya Iyer',
        'ananya.iyer@gmail.com',
        '+91 98450 11223',
        'Bengaluru',
        '2025-11-04',
        14,
        3,
        'Active',
      ],
      [
        'Rahul Verma',
        'rahul.verma@outlook.com',
        '+91 99860 44112',
        'Bengaluru',
        '2025-12-19',
        9,
        1,
        'Active',
      ],
      [
        'Fatima Sheikh',
        'fatima.sheikh@gmail.com',
        '+91 90080 77341',
        'Hyderabad',
        '2026-01-07',
        6,
        2,
        'Active',
      ],
      [
        'Joseph Mathew',
        'joseph.mathew@gmail.com',
        '+91 94470 20915',
        'Kochi',
        '2026-01-22',
        11,
        4,
        'Active',
      ],
      [
        'Sneha Kulkarni',
        'sneha.kulkarni@gmail.com',
        '+91 98230 65540',
        'Pune',
        '2026-02-11',
        4,
        0,
        'Active',
      ],
      [
        'Dev Trivedi',
        'dev.trivedi@gmail.com',
        '+91 97250 30188',
        'Ahmedabad',
        '2026-02-28',
        2,
        0,
        'Blocked',
      ],
      [
        'Meenakshi Rao',
        'meenakshi.rao@gmail.com',
        '+91 98800 91276',
        'Mysuru',
        '2026-03-15',
        8,
        2,
        'Active',
      ],
      [
        'Arjun Nair',
        'arjun.nair@gmail.com',
        '+91 97440 55810',
        'Bengaluru',
        '2026-04-02',
        5,
        1,
        'Active',
      ],
      [
        'Kavya Reddy',
        'kavya.reddy@gmail.com',
        '+91 90300 47765',
        'Hyderabad',
        '2026-04-26',
        3,
        1,
        'Active',
      ],
      [
        'Imran Qureshi',
        'imran.qureshi@gmail.com',
        '+91 99670 12084',
        'Nagpur',
        '2026-05-18',
        1,
        0,
        'Blocked',
      ],
    ],
  },
];

/**
 * Last-generated date per report, index-aligned with `OPS_REPORT_DEFS`
 * (design `OpsDB.reportsGen` — entries become "just now" after an export).
 */
export const OPS_REPORTS_GEN: readonly string[] = [
  'June 12, 2026',
  'June 12, 2026',
  'June 09, 2026',
  'June 09, 2026',
  'June 06, 2026',
  'June 04, 2026',
];
